################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (9-2020-q2-update)
################################################################################

# Add inputs and outputs from these tool invocations to the build variables 
C_SRCS += \
D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/freertos.c \
D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/main.c \
D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/stm32f7xx_hal_msp.c \
D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/stm32f7xx_hal_timebase_tim.c \
D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/stm32f7xx_it.c \
../Application/User/Core/syscalls.c \
../Application/User/Core/sysmem.c 

C_DEPS += \
./Application/User/Core/freertos.d \
./Application/User/Core/main.d \
./Application/User/Core/stm32f7xx_hal_msp.d \
./Application/User/Core/stm32f7xx_hal_timebase_tim.d \
./Application/User/Core/stm32f7xx_it.d \
./Application/User/Core/syscalls.d \
./Application/User/Core/sysmem.d 

OBJS += \
./Application/User/Core/freertos.o \
./Application/User/Core/main.o \
./Application/User/Core/stm32f7xx_hal_msp.o \
./Application/User/Core/stm32f7xx_hal_timebase_tim.o \
./Application/User/Core/stm32f7xx_it.o \
./Application/User/Core/syscalls.o \
./Application/User/Core/sysmem.o 


# Each subdirectory must supply rules for building sources it contributes
Application/User/Core/freertos.o: D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/freertos.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Config" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusPlatformIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusService/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/RingBuffer/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard/Inc" -I"C:/TouchGFX/4.18.1/touchgfx/lib/core/cortex_m7/gcc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/main.o: D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/main.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Config" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusPlatformIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusService/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/RingBuffer/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard/Inc" -I"C:/TouchGFX/4.18.1/touchgfx/lib/core/cortex_m7/gcc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32f7xx_hal_msp.o: D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/stm32f7xx_hal_msp.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Config" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusPlatformIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusService/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/RingBuffer/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard/Inc" -I"C:/TouchGFX/4.18.1/touchgfx/lib/core/cortex_m7/gcc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32f7xx_hal_timebase_tim.o: D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/stm32f7xx_hal_timebase_tim.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Config" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusPlatformIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusService/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/RingBuffer/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard/Inc" -I"C:/TouchGFX/4.18.1/touchgfx/lib/core/cortex_m7/gcc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/stm32f7xx_it.o: D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/Core/Src/stm32f7xx_it.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Config" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusPlatformIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusService/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/RingBuffer/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard/Inc" -I"C:/TouchGFX/4.18.1/touchgfx/lib/core/cortex_m7/gcc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"
Application/User/Core/%.o: ../Application/User/Core/%.c Application/User/Core/subdir.mk
	arm-none-eabi-gcc "$<" -mcpu=cortex-m7 -std=gnu11 -g3 -DUSE_HAL_DRIVER -DSTM32F746xx -DDEBUG -c -I../../Core/Inc -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Config" -I../../TouchGFX/App -I../../TouchGFX/target/generated -I../../TouchGFX/target -I../../Drivers/STM32F7xx_HAL_Driver/Inc -I../../Drivers/STM32F7xx_HAL_Driver/Inc/Legacy -I../../Middlewares/Third_Party/FreeRTOS/Source/include -I../../Middlewares/Third_Party/FreeRTOS/Source/portable/GCC/ARM_CM7/r0p1 -I../../Drivers/CMSIS/Device/ST/STM32F7xx/Include -I../../Drivers/CMSIS/Include -I../../Middlewares/ST/touchgfx/framework/include -I../../TouchGFX/generated/fonts/include -I../../TouchGFX/generated/gui_generated/include -I../../TouchGFX/generated/images/include -I../../TouchGFX/generated/texts/include -I../../TouchGFX/gui/include -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS_V2 -I../../Middlewares/Third_Party/FreeRTOS/Source/CMSIS_RTOS -I../../Drivers/BSP/STM32746G-Discovery -I../../Drivers/BSP/Components/ft5336 -I../../LIBJPEG/App -I../../LIBJPEG/Target -I../../Middlewares/Third_Party/LibJPEG/include -I../../TouchGFX/generated/videos/include -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusPlatformIf/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/ModbusService/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/RingBuffer/Inc" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard" -I"D:/Job/ModbusBedsideController/FinalProject/Modbus_Bedside_Controller_Dualport/STM32CubeIDE/Middlewares/Modbus/Standard/Inc" -I"C:/TouchGFX/4.18.1/touchgfx/lib/core/cortex_m7/gcc" -Og -ffunction-sections -fdata-sections -Wall -fstack-usage -MMD -MP -MF"$(@:%.o=%.d)" -MT"$@" --specs=nano.specs -mfpu=fpv5-sp-d16 -mfloat-abi=hard -mthumb -o "$@"

clean: clean-Application-2f-User-2f-Core

clean-Application-2f-User-2f-Core:
	-$(RM) ./Application/User/Core/freertos.d ./Application/User/Core/freertos.o ./Application/User/Core/main.d ./Application/User/Core/main.o ./Application/User/Core/stm32f7xx_hal_msp.d ./Application/User/Core/stm32f7xx_hal_msp.o ./Application/User/Core/stm32f7xx_hal_timebase_tim.d ./Application/User/Core/stm32f7xx_hal_timebase_tim.o ./Application/User/Core/stm32f7xx_it.d ./Application/User/Core/stm32f7xx_it.o ./Application/User/Core/syscalls.d ./Application/User/Core/syscalls.o ./Application/User/Core/sysmem.d ./Application/User/Core/sysmem.o

.PHONY: clean-Application-2f-User-2f-Core

